spring:
  application:
    name: JavaWork3

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javawork3
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update

user:
  init:
    password: 123456

regex:
  filter: (.*(js|css))|(.*(login|register|change).*)

interceptor:
  resource:
    static: .*(.html|.css|.js)
    admin: .*admin.*
